name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          set -x
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
            source ~/.bashrc  # or source ~/.bash_profile, or source ~/.zshrc
            cd ~/websites/iokasti
            git pull
            npm install
            npm run build
            cd ~/websites/iokasti/iokasti-client
            npm install
            npm run build
            cd ~/websites/iokasti
            pm2 reload ecosystem.config.js
            pm2 save
          "
