name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}

      - name: Install Node.js
        uses: dcodeIO/setup-node-nvm@master


      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no -t ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} <<'EOF'
            [ -s "$HOME/.nvm/nvm.sh" ] && \. "$HOME/.nvm/nvm.sh"
            cd ~/websites/iokasti
            git pull
            nvm install
            nvm use
            cd ~/websites/iokasti/iokasti-backend
            npm install
            npm run production
            cd ~/websites/iokasti/iokasti-client
            npm install
            npm run build
            cd ~/websites/iokasti
            pm2 reload ecosystem.config.js
            pm2 save
          EOF